# GitHub Actions Configuration for integrated testing using pytest
name: Test package
run-name: "Running tests as ${{ github.actor }} has pushed changes"
on: [push]

jobs:
  build:

    strategy:
      matrix:
         os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH      

      - name: Install dependencies
        run: poetry install --with dev,test,docs

      - name: Test with pytest
        run: poetry run pytest --junitxml=junit/test-results.xml --cov=dummyproject tests/

      - name: Upload coverage to Codecov
        if: runner.os == 'Windows'
        uses: codecov/codecov-action@v3
